'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("OverTool_GUI.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Copyright (c) 2002, Xiph.org Foundation
        '''
        '''Copyright (c) 2009-2016, Adam Gashlin
        '''
        '''
        '''
        '''Redistribution and use in source and binary forms, with or without
        '''modification, are permitted provided that the following conditions
        '''are met:
        '''
        '''
        '''
        '''- Redistributions of source code must retain the above copyright
        '''notice, this list of conditions and the following disclaimer.
        '''
        '''
        '''
        '''- Redistributions in binary form must reproduce the above copyright
        '''notice, this list of conditions and the following disclaimer in the
        '''documentati [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property COPYING() As String
            Get
                Return ResourceManager.GetString("COPYING", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property Magick_NET_Q16_AnyCPU() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Magick_NET_Q16_AnyCPU", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
        '''
        '''1. Magick.NET copyright:
        '''
        '''Copyright 2013-2017 Dirk Lemstra &lt;https://github.com/dlemstra/Magick.NET/&gt;
        '''
        '''Licensed under the ImageMagick License (the &quot;License&quot;); you may not use this
        '''file except in compliance with the License. You may obtain a copy of the License
        '''at
        '''
        ''' https://www.imagemagick.org/script/license.php
        '''
        '''Unless required by applicable law or agreed to in writing, software distributed
        '''under the License is dist [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property MagickCopyright() As String
            Get
                Return ResourceManager.GetString("MagickCopyright", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property packed_codebooks_aoTuV_603() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("packed_codebooks_aoTuV_603", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property revorb() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("revorb", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to @echo off
        '''
        '''for /f &quot;delims=&quot; %%f in (&apos;dir /s/b/a-d &quot;*.wem&quot;&apos;) do (ww2ogg.exe --pcb packed_codebooks_aoTuV_603.bin &quot;%%f&quot;)
        '''for /f &quot;delims=&quot; %%f in (&apos;dir /s/b/a-d &quot;*.ogg&quot;&apos;) do (revorb.exe &quot;%%f&quot;)
        '''
        '''echo Job Complete!.
        '''</summary>
        Friend ReadOnly Property script() As String
            Get
                Return ResourceManager.GetString("script", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property ww2ogg() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("ww2ogg", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
    End Module
End Namespace
